language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mpradipto/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true mpradipto/docker-react npm run test

